### ISSUE TITLE
Tensorflow version

### ISSUE THREAD

**Issue by GlockPL** [gaborvecsei/SLE-GAN#9]
What version of tensorflow should I use?
Currently I have installed 2.4.1 and first step freezes, nothing happens.
GPU-Z shows that gpu ram is filled but power consumption is 20%.

**Comment by gaborvecsei** [comment]
As long as it's TF >=2.0 it should be fine.

If the VRAM is filled, then you should reduce the batch size of train on a GPU with more VRAM.
